# Generated by Django 6.0.5 on 2026-05-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('passenger', 'Passenger'), ('rider', 'Rider'), ('event_organiser', 'Event Organiser'), ('tour_guide', 'Tour Guide')], default='passenger', max_length=20),
        ),
    ]
