# VEHICLE INTENT
VIEW_VEHICLE = "VIEW_VEHICLE"

CREATE_VEHICLE = "CREATE_VEHICLE"

UPDATE_VEHICLE = "UPDATE_VEHICLE"


# DRIVER ROUTE INTENT
CREATE_ROUTE = "CREATE_ROUTE"
VIEW_ROUTES = "VIEW_ROUTES"
UPDATE_ROUTE = "UPDATE_ROUTE"
DELETE_ROUTE = "DELETE_ROUTE"

# RIDE BOOKING INTENT
BOOK_RIDE = "BOOK_RIDE"

UPDATE_BOOKING = "UPDATE_BOOKING"

CANCEL_BOOKING = "CANCEL_BOOKING"
VIEW_RIDES = "VIEW_RIDES"
VIEW_RIDE_REQUESTS = (
    "VIEW_RIDE_REQUESTS"
)

ACCEPT_BOOKING = "ACCEPT_BOOKING"

REJECT_BOOKING = "REJECT_BOOKING"

UPDATE_BOOKING_PRICE = (
    "UPDATE_BOOKING_PRICE"
)

SUPPORT = "SUPPORT"

GREETING = "GREETING"

UNKNOWN = "UNKNOWN"