# Generated by Django 6.0.5 on 2026-05-19 08:45

import django.db.models.deletion
import rideshare.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DriverRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_name", models.CharField(max_length=255)),
                ("end_name", models.CharField(max_length=255)),
                ("start_lat", models.FloatField()),
                ("start_lng", models.FloatField()),
                ("end_lat", models.FloatField()),
                ("end_lng", models.FloatField()),
                ("distance_meters", models.FloatField()),
                ("duration_seconds", models.FloatField()),
                ("encoded_polyline", models.TextField()),
                ("route_geometry", models.JSONField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_routes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RideBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_id",
                    models.CharField(
                        db_index=True, editable=False, max_length=50, unique=True
                    ),
                ),
                ("pickup_name", models.CharField(max_length=255)),
                ("destination_name", models.CharField(max_length=255)),
                ("pickup_lat", models.FloatField()),
                ("pickup_lng", models.FloatField()),
                ("destination_lat", models.FloatField()),
                ("destination_lng", models.FloatField()),
                (
                    "estimated_price",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "final_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("distance_meters", models.FloatField()),
                ("route_geometry", models.JSONField()),
                ("encoded_polyline", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RIDER_SELECTED", "Rider Selected"),
                            ("PAYMENT_PENDING", "Payment Pending"),
                            ("CONFIRMED", "Confirmed"),
                            ("IN_PROGRESS", "In Progress"),
                            ("OTP_PENDING", "OTP Pending"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                (
                    "ride_completion_otp",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("otp_generated_at", models.DateTimeField(blank=True, null=True)),
                ("otp_verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "passenger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passenger_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "selected_rider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="selected_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("PAYSTACK", "Paystack")],
                        default="PAYSTACK",
                        max_length=50,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="NGN", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                            ("REFUNDED", "Refunded"),
                        ],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                ("payment_reference", models.CharField(max_length=255, unique=True)),
                (
                    "access_code",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("authorization_url", models.URLField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("gateway_response", models.JSONField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "passenger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ride_earnings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="rideshare.ridebooking",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RideBookingResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "response",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAYMENT_PENDING", "Payment Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "updated_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="rideshare.ridebooking",
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rideshare.driverroute",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RideOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=6)),
                ("is_verified", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rideshare.ridebooking",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "licence",
                    models.FileField(
                        blank=True, null=True, upload_to=rideshare.models.upload_data
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Car", "Car"),
                            ("Bus", "Bus"),
                            ("Tricycle", "Tricycle"),
                            ("Motorcycle", "Motorcycle"),
                            ("Bicycle", "Bicycle"),
                            ("Train", "Train"),
                            ("Boat", "Boat"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("brand", models.CharField(max_length=125, null=True)),
                ("plate_no", models.CharField(max_length=125, null=True, unique=True)),
                ("seat_cap", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicle",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
