# Generated by Django 6.0.5 on 2026-05-14 20:51

import django.db.models.deletion
import rideshare.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence', models.FileField(blank=True, null=True, upload_to=rideshare.models.upload_data)),
                ('type', models.CharField(choices=[('Car', 'Car'), ('Bus', 'Bus'), ('Tricycle', 'Tricycle'), ('Motorcycle', 'Motorcycle'), ('Bicycle', 'Bicycle'), ('Train', 'Train'), ('Boat', 'Boat')], max_length=20, null=True)),
                ('brand', models.CharField(max_length=125, null=True)),
                ('plate_no', models.CharField(max_length=125, null=True, unique=True)),
                ('seat_cap', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
