# Generated by Django 6.0.5 on 2026-05-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rideshare", "0002_driverroute_ridebooking_ridebookingresponse_rideotp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ridebookingresponse",
            name="response",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PAYMENT_PENDING", "Payment Pending"),
                    ("ACCEPTED", "Accepted"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                max_length=50,
            ),
        ),
    ]
