# Generated by Django 6.0.5 on 2026-05-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rideshare", "0004_alter_ridebookingresponse_response_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="ridebooking",
            name="otp_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ridebooking",
            name="otp_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ridebooking",
            name="ride_completion_otp",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="ridebooking",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("RIDER_SELECTED", "Rider Selected"),
                    ("PAYMENT_PENDING", "Payment Pending"),
                    ("CONFIRMED", "Confirmed"),
                    ("IN_PROGRESS", "In Progress"),
                    ("OTP_PENDING", "OTP Pending"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=50,
            ),
        ),
    ]
