BOOKING_FLOW = "BOOKING_FLOW"

AWAITING_PICKUP = "AWAITING_PICKUP"

AWAITING_DESTINATION = (
    "AWAITING_DESTINATION"
)

AWAITING_PRICE_UPDATE = (
    "AWAITING_PRICE_UPDATE"
)

VIEWING_RIDE_STATUS = (
    "VIEWING_RIDE_STATUS"
)

COMPLETED = "COMPLETED"