RIDER_REQUEST_FLOW = "RIDER_REQUEST_FLOW"

SELECTING_RIDE_REQUEST = "SELECTING_RIDE_REQUEST"

UPDATING_RIDE_PRICE = "UPDATING_RIDE_PRICE"

RIDE_OFFER_FLOW = "RIDE_OFFER_FLOW"

RIDE_PRICE_OFFER = "RIDE_PRICE_OFFER"

SELECTING_RIDER = "SELECTING_RIDER"
