ROUTE_FLOW = "ROUTE_FLOW"

ASK_ROUTE_START = "ASK_ROUTE_START"

ASK_ROUTE_DESTINATION = "ASK_ROUTE_DESTINATION"

ROUTE_MENU = "ROUTE_MENU"


ASK_ROUTE_TO_UPDATE = (
    "ASK_ROUTE_TO_UPDATE"
)

ASK_NEW_ROUTE_START = (
    "ASK_NEW_ROUTE_START"
)

ASK_NEW_ROUTE_DESTINATION = (
    "ASK_NEW_ROUTE_DESTINATION"
)

ASK_ROUTE_TO_DELETE = (
    "ASK_ROUTE_TO_DELETE"
)

CONFIRM_ROUTE_DELETE = (
    "CONFIRM_ROUTE_DELETE"
)