# Generated by Django 6.0.5 on 2026-05-19 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=20, unique=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("START", "START"),
                            ("ASK_ROLE", "ASK_ROLE"),
                            ("ASK_EMAIL", "ASK_EMAIL"),
                            ("VERIFY_OTP", "VERIFY_OTP"),
                            ("ASK_FIRST_NAME", "ASK_FIRST_NAME"),
                            ("COMPLETED", "COMPLETED"),
                        ],
                        default="START",
                        max_length=50,
                    ),
                ),
                ("context", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="whatsapp_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
