# Generated by Django 6.0.5 on 2026-05-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_conversationsession_last_interaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationsession',
            name='current_action',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conversationsession',
            name='current_menu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
