# Generated by Django 6.0.5 on 2026-05-16 19:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0003_conversationsession_current_action_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversationsession',
            old_name='current_action',
            new_name='current_step',
        ),
        migrations.RenameField(
            model_name='conversationsession',
            old_name='current_menu',
            new_name='current_workflow',
        ),
        migrations.RemoveField(
            model_name='conversationsession',
            name='last_interaction',
        ),
        migrations.RemoveField(
            model_name='conversationsession',
            name='state',
        ),
        migrations.AddField(
            model_name='conversationsession',
            name='last_ai_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversationsession',
            name='last_user_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conversationsession',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
