# Generated by Django 6.0.5 on 2026-05-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "conversation",
            "0004_rename_current_action_conversationsession_current_step_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="conversationsession",
            old_name="current_step",
            new_name="current_action",
        ),
        migrations.RenameField(
            model_name="conversationsession",
            old_name="current_workflow",
            new_name="current_menu",
        ),
        migrations.RemoveField(
            model_name="conversationsession",
            name="last_ai_response",
        ),
        migrations.RemoveField(
            model_name="conversationsession",
            name="last_user_message",
        ),
        migrations.AddField(
            model_name="conversationsession",
            name="last_interaction",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="conversationsession",
            name="state",
            field=models.CharField(default="START", max_length=100),
        ),
        migrations.AlterField(
            model_name="conversationsession",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
