# Onboarding State

START = "START"

ASK_MAIN_ROLE = "ASK_MAIN_ROLE"

ASK_SERVICE_PROVIDER_ROLE = (
    "ASK_SERVICE_PROVIDER_ROLE"
)

ASK_FIRST_NAME = "ASK_FIRST_NAME"

ASK_LAST_NAME = "ASK_LAST_NAME"

ASK_EMAIL = "ASK_EMAIL"

VERIFY_OTP = "VERIFY_OTP"

MAIN_MENU = "MAIN_MENU"

# Rider Profile state
RIDER_PROFILE_MENU  = "RIDER_PROFILE_MENU"

# Vehicle state

ASK_VEHICLE_TYPE = "ASK_VEHICLE_TYPE"

ASK_VEHICLE_BRAND = "ASK_VEHICLE_BRAND"

ASK_VEHICLE_PLATE_NO = (
    "ASK_VEHICLE_PLATE_NO"
)

ASK_VEHICLE_SEAT_CAP = (
    "ASK_VEHICLE_SEAT_CAP"
)


# Route State

RIDER_ROUTE_MENU = "RIDER_ROUTE_MENU"

ASK_ROUTE_START = "ASK_ROUTE_START"

ASK_ROUTE_DESTINATION = (
    "ASK_ROUTE_DESTINATION"
)

# Booking State

ASK_PICKUP_LOCATION = "ASK_PICKUP_LOCATION"


ASK_DESTINATION_LOCATION = (
    "ASK_DESTINATION_LOCATION"
)

SELECT_RIDER = (
    "SELECT_RIDER"
)

CONFIRM_BOOKING = (
    "CONFIRM_BOOKING"
)

ASK_NEW_BOOKING_PRICE = (
    "ASK_NEW_BOOKING_PRICE"
)

SELECT_BOOKING_RIDER = (
    "SELECT_BOOKING_RIDER"
)

# Event creation state

ASK_EVENT_NAME = "ASK_EVENT_NAME"
ASK_EVENT_LOCATION = "ASK_EVENT_LOCATION"
ASK_EVENT_START_DATE = "ASK_EVENT_START_DATE"
ASK_EVENT_END_DATE = "ASK_EVENT_END_DATE"
ASK_EVENT_START_TIME = "ASK_EVENT_START_TIME"
ASK_EVENT_END_TIME = "ASK_EVENT_END_TIME"

EVENT_COMPLETED = "EVENT_COMPLETED"



# AI FLow constants

VIEW_BOOKINGS = "VIEW_BOOKINGS"

VIEW_BOOKING_DETAILS = "VIEW_BOOKING_DETAILS"

CANCEL_BOOKING_CONFIRMATION = (
    "CANCEL_BOOKING_CONFIRMATION"
)

UPDATE_BOOKING_PICKUP = (
    "UPDATE_BOOKING_PICKUP"
)

UPDATE_BOOKING_DESTINATION = (
    "UPDATE_BOOKING_DESTINATION"
)